const ADD_EQUIPMENT = 'ADD_EQUIPMENT';
const REMOVE_EQUIPMENT = 'REMOVE_EQUIPMENT';
const UPDATE_EQUIPMENT = 'UPDATE_EQUIPMENT';
const REMOVE_ALL_USER_EQUIPMENTS = 'REMOVE_ALL_USER_EQUIPMENTS';

export {
  ADD_EQUIPMENT,
  REMOVE_EQUIPMENT,
  UPDATE_EQUIPMENT,
  REMOVE_ALL_USER_EQUIPMENTS,
};
